### ISSUE TITLE
Does this work for load-balanced environments?

### ISSUE THREAD

**Issue by missmatsuko** [jan-dh/translator#1]
It looks like it works similarly to [enupal/translate](https://github.com/enupal/translate) in that it saves the strings to the translation file, so I think it would have the same issue with load-balanced environments: https://github.com/enupal/translate/issues/22

**Comment by jan-dh** [comment]
It will indeed share those issues, since that's the nature of the static translation implementation made by YII2 and Craft. This field type only provides a layer on top of those implementations.
