### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [jan-dh/translator#11]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `jandh\translator\assetbundles\translatorfield\TranslatorAsset` located in `./vendor/jandh/translator/src/assetbundles/translatorfield/TranslatorFieldAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/translatorfield/TranslatorFieldAsset.php src/assetbundles/translatorfield/TranslatorAsset.php
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by circa1983** [comment]
I think you will also have to update:
`git mv src/fields/Translator.php src/fields/TranslatorField.php`

_NB: my folk **does not** contain the fixes you need!!_

**Comment by jan-dh** [comment]
Alright, updated all my code, also the one mentioned by @circa1983. The plugin store doesn't seem to pick up on my updated though 🤔

**Comment by jan-dh** [comment]
Alright, it's live

**Comment by brandonkelly** [comment]
Looks good on my end. Thanks!
