### ISSUE TITLE
Translated Strings being saved but not shown on interface

### ISSUE THREAD

**Issue by funkysoul** [jan-dh/translator#13]
Great plugin, exactly what I was looking for. 
I'm experiencing a "little" issue with the plugin.

I've setup a translator field assigned it to "globals" (also tried with a normal section)
The interface works, the single "strings" are yellow marked, when I "translate" strings, the site.php is stored correctly.

But when I revisit the global section the fields are empty. 
I'm running a 2 language website (DE, FR) the site.php is only stored in the original language, when translating FR, the DE site.php is "resaved" with the french values. 

Running the latest version of Craft

**Comment by jan-dh** [comment]
Haven't tested it on latest Craft version, wil have a look. Can you give me some info on your server settings? php version etc?

**Comment by funkysoul** [comment]
PHP version | 7.4.14
FreeBSD 11.4-RELEASE-p2
MySQL 5.5.5
Imagick 3.4.4 (ImageMagick 6.9.11-6)
Craft Pro 3.6.3
Yii 2.0.40
Twig v2.14.3
Guzzle 7.2.0

**Comment by jan-dh** [comment]
@funkysoul can you test the new version? I'm still waiting for the plugin store to pick it up, but you can test the code straight from the repo.
