### ISSUE TITLE
TypeError when using Translator Field in globals

### ISSUE THREAD

**Issue by sanderpotjer** [jan-dh/translator#14]
Thanks for this plugin! 

Setup:
- 4 sites in Craft, for NL, EN, DE and ES language, each with their own handle (set to language)
- Craft CMS 3.6.6
- Translator 1.1.4

Translator field is assigned to "Global" set and only field assigned. 

When trying to access the global set for editing in the backend, for example the ES version: `admin/globals/es/static` the following error is shown: 

`Argument 1 passed to craft\services\Sites::getSiteByHandle() must be of the type string, null given, called in /vendor/jandh/translator/src/fields/TranslatorField.php on line 120`

Introduced by https://github.com/jan-dh/translator/commit/fdd9aa2c7f15d0a4acf46e18504571e6630b0e33 (which indeed addressed another issue). 

The line `$currentSite = Craft::$app->request->getParam('site');` is empty, not returning the site handle (for the Globals at least).

**Comment by jan-dh** [comment]
@sanderpotjer this should be fixed with the new release.

**Comment by sanderpotjer** [comment]
@jan-dh confirmed, thanks! 👍
