### ISSUE TITLE
Feature Request: provide a single field that shows all translations by default.

### ISSUE THREAD

**Issue by TomDeSmet** [jan-dh/translator#3]
This could be a handy plugin, but to me it would seem more appropriate to have a global field that contains all translations at once and is automatically updated when there are more translations in your site.php files instead of needing to create multiple fields per entryType.

Because multiple translations can be used in multiple templates, you only want to translate this once, hence to put it in a global for example.

Is this something you could easily do? I suppose you have all the things you need working already, so it seems a bit overkill to write a similar plugin.

**Comment by jan-dh** [comment]
I have thought about the approach above you described, for the exact same reason you describe: a translation can used in multiple templates. However, the reasons for taking my current approach were the following:

**More control**
By allowing the developers to select the translations you want available for the authors and in what place, you have full control. I don't personally like "automaticly" adding all translations in to one place. For example: sometimes only a certain group of authors has access to certain sections of the website but needs access to a couple of the translations of a particular section of the website. One global field would make such a think impossible.

**Author experience**
As an author you would have to manage translations in a place that has no real connection with the content you are editing. This can be often confusion, as you don't have access to the templates to see where what translation occurs. This field was created just to make sure you could add translations related to the page to the page, so the author can edit everything the whole thing in one place. Moving this to a global would make it less obvious for authors what snippet belongs to what page, and would require them to do extra clicks. The whole issue I'm trying to work around with this field.


The field currently shows wether the string is already translated, being present in multiple places doesn't pose a big issue in that sense.

The solution you are asking for could very easily be achieved by creating a single field, selecting all your available translations and add that field to a global set?

**Comment by TomDeSmet** [comment]
That's true, however, every time a new translation is added to the site.php you'll need to manually update that field also. Just a minor issue that could potentially cause issues when working with multiple people on the same project (especially in future updates).

Could you make it an option? Add my request as a separate field type for example? So people have the choice?

**Comment by jan-dh** [comment]
The option you're looking for does already exists, it's what the enupal plugin does? Will consider it but at the moment not convinced tbh.

**Comment by TomDeSmet** [comment]
True, didn't know that one. I'll test it out. Thanks.
