### ISSUE TITLE
Craft V4 support

### ISSUE THREAD

**Issue by wakoodi** [jan-dh/translator#39]
Hi, 

Is this plugin going to be upgraded to support Craft V4? 

Thanks in advance.

**Comment by jan-dh** [comment]
If you'd like this I could have a look at this yep.

**Comment by wakoodi** [comment]
That would be great! I really like the easy useability of this plugin and it's the only one that prevents the upgrade to Craft 4.

Thanks in advance!

**Comment by jan-dh** [comment]
Will have a look at this but I'm pretty swamped right now, so don't expect a quick update on this.

**Comment by jan-dh** [comment]
Hi @wakoodi made some time today to upgrade the plugin. Took it for a spin and everything looked fine, so if you want you can take it for a spin! Let me know if you run into something.

**Comment by wakoodi** [comment]
Hi, It works! Thank you!
