### ISSUE TITLE
Error exception: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory

### ISSUE THREAD

**Issue by craftedsystems** [jan-dh/translator#5]
Control panel error while creating or editing fields.

https://github.com/jan-dh/translator/blob/f17be242d4a1376c17968d6d4127a1435bc436a0/src/fields/Translator.php#L95

Craft 3.3.18.4
PHP 7.4.1

**Comment by Photon89** [comment]
I just ran into the same problem. Looks like foreach now also lists "." and ".." as files in a directory, so when looping over them the loop variable $value also gets the values "." and "..".

**Comment by orajiakuchibuchi** [comment]
pleae how do you resolve this?

**Comment by Photon89** [comment]
See discussion here: https://github.com/maglnet/ComposerRequireChecker/issues/172

**Comment by jan-dh** [comment]
Final

**Comment by jan-dh** [comment]
This should be fixed with the latest update
