### ISSUE TITLE
Failed to open stream od directory

### ISSUE THREAD

**Issue by app-solutions-pl** [jan-dh/translator#9]
There is an error while parsing twig templates while using partials in subdirectories named "templates/_components/", etc. Error is risen in \vendor\jandh\translator\src\fields\Translator.php:95. It tries to read directory as a file.

yii\base\ErrorException: file_get_contents(C:\inetpub\www\test\craft\templates\_components): failed to open stream: Permission denied in C:\inetpub\www\test\craft\vendor\jandh\translator\src\fields\Translator.php:95

Fixed by adding is_file check:

    public function getTranslatablesFromTemplates(&$files){
        $translatables = array();

        foreach ($files as $value) {
			if(is_file($value)) {
				$html = file_get_contents($value);
				if (preg_match_all('/{{([^}]+)\|t(?:ranslate)?\b(?:\|([^}]+)|\s*)}}/', $html, $matches)) {
					foreach ($matches[1] as $item) {
						$clean = substr(trim($item), 1, -1);
						$translatables[$clean] = $clean;
					}
				}
			}
        }
        return array_unique($translatables);
    }

**Comment by jan-dh** [comment]
Sorry, lost track of this. Updated, should appear online soon.
